//! Non-streaming response conversion for `anthropic_messages -> openai_chat_completions`.

use super::citations::text_block_annotations;
use crate::protocol::anthropic::messages::{ContentBlock, Message, StopReason};
use crate::protocol::openai::chat_completions::{
    ChatChoice, ChatChoiceLogprobs, ChatCompletionResponseMessage, CreateChatCompletionResponse,
    Role,
};
use crate::translation::{TranslationError, TranslationResult};

impl TryFrom<&Message> for CreateChatCompletionResponse {
    type Error = TranslationError;

    fn try_from(message: &Message) -> TranslationResult<Self> {
        let mut text_parts: Vec<String> = Vec::new();
        let mut tool_calls = Vec::new();
        let mut annotations = Vec::new();

        for block in &message.content {
            match block {
                ContentBlock::Text(block) => {
                    let base_offset = text_parts.iter().map(|text| text.chars().count()).sum();
                    annotations.extend(text_block_annotations(block, base_offset));
                    text_parts.push(block.text.clone());
                }
                ContentBlock::ToolUse(block) => tool_calls.push(block.try_into()?),
                // OpenAI Chat response messages only expose `content` plus
                // `tool_calls`. Other Anthropic response blocks (thinking,
                // redacted thinking, server-tool artifacts) have no safe Chat
                // message field, so they are skipped with a trace log to keep
                // silent drops observable.
                skipped => {
                    tracing::trace!(
                        discriminant = ?std::mem::discriminant(skipped),
                        "skipping Anthropic response block with no Chat-representable field"
                    );
                }
            }
        }

        // Chat Completions cannot preserve Anthropic block interleaving in a
        // non-streaming assistant message, so text blocks are flattened.
        let content = text_parts.join("");
        let refusal = message_refusal(message, &content);
        let content = if refusal.is_some() {
            String::new()
        } else {
            content
        };

        if content.is_empty() && refusal.is_none() && tool_calls.is_empty() {
            return Err(TranslationError::InvalidPayload(
                "Anthropic message response has no Chat-representable content, refusal, or tool_use blocks"
                    .to_string(),
            ));
        }

        Ok(Self {
            // Anthropic message ids are not Chat Completion ids; keep the
            // upstream id embedded while presenting an OpenAI-compatible shape.
            id: format!("chatcmpl_{}", message.id),
            choices: vec![ChatChoice {
                index: 0,
                message: ChatCompletionResponseMessage {
                    content: (!content.is_empty()).then_some(content),
                    // Chat has only a refusal string; Anthropic refusal category
                    // has no equivalent Chat response field.
                    refusal,
                    tool_calls: (!tool_calls.is_empty()).then_some(tool_calls),
                    // Only Anthropic web-search citations can be represented as
                    // OpenAI Chat URL annotations. Other citation location types
                    // lack URL annotation equivalents.
                    annotations: (!annotations.is_empty()).then_some(annotations),
                    role: Role::Assistant,
                    audio: None,
                },
                finish_reason: message.stop_reason.map(Into::into),
                // Anthropic does not expose Chat-style token logprobs on message responses.
                logprobs: None::<ChatChoiceLogprobs>,
            }],
            // Anthropic message responses do not carry a Unix creation timestamp.
            created: 0,
            model: message.model.clone(),
            // Anthropic response `usage.service_tier` is not the same shape as OpenAI
            // Chat's response-level service tier, so avoid inventing a value.
            service_tier: None,
            object: "chat.completion".to_string(),
            usage: Some((&message.usage).into()),
        })
    }
}

fn message_refusal(message: &Message, content: &str) -> Option<String> {
    if !matches!(message.stop_reason, Some(StopReason::Refusal)) {
        return None;
    }

    // OpenAI Chat `refusal` is the refusal message generated by the model.
    // Anthropic text content is the closest user-visible refusal message;
    // `stop_details.explanation` explains why the model refused, so use it
    // only when Anthropic did not return visible refusal text.
    (!content.is_empty())
        .then(|| content.to_string())
        .or_else(|| {
            message
                .stop_details
                .as_ref()
                .and_then(|details| details.explanation.clone())
        })
}

#[cfg(test)]
#[path = "response_tests.rs"]
mod tests;
